# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

before_script:
  - Rscript -e 'remotes::install_cran(c("devtools", "covr", "pkgdown", "spelling"))'
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo tlmgr install framed titling cancel; fi

addons:
  apt:
    update: true
    packages:
      - libudunits2-dev # for udunits2
      - libgeos-dev # for sf
      - libproj-dev # for sf
      - libgdal-dev # for sf

deploy:
  - provider: script
    script: Rscript -e 'pkgdown::deploy_site_github()'
    skip_cleanup: true
    on:
      branch: master
      condition: "$DEPLOY = true"
