# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

armaMatMult <- function(A, B) {
    .Call(`_bioRgeo_armaMatMult`, A, B)
}

eigenMatMult <- function(A, B) {
    .Call(`_bioRgeo_eigenMatMult`, A, B)
}

eigenMapMatMult <- function(A, B) {
    .Call(`_bioRgeo_eigenMapMatMult`, A, B)
}

hello <- function() {
    .Call(`_bioRgeo_hello`)
}

