# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ProdMat <- function(A, B) {
    .Call(`_bioRgeo_ProdMat`, A, B)
}

abcw <- function(N, thin) {
    .Call(`_bioRgeo_abcw`, N, thin)
}

